package handler

import (
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	templates "github.com/Muxcore-Media/admin-ui/templ"
)

var (
	spoolTrustMu   sync.Mutex
	spoolTrustRoot = envOr("ADMIN_UI_SPOOL_TRUST_DIR", filepath.Join(os.TempDir(), "muxcore-spool-trust"))
)

type spoolTrustFile struct {
	RequireSignature  bool                `json:"require_signature"`
	AllowedPublishers string              `json:"allowed_publishers"`
	Keys              []spoolTrustKeyMeta `json:"keys"`
}

type spoolTrustKeyMeta struct {
	ID          string `json:"id"`
	Label       string `json:"label"`
	Fingerprint string `json:"fingerprint"`
	Filename    string `json:"filename"`
	AddedAt     string `json:"added_at"`
}

func spoolTrustDir() string {
	return spoolTrustRoot
}

func spoolTrustKeysDir() string {
	return filepath.Join(spoolTrustDir(), "keys")
}

func spoolTrustJSONPath() string {
	return filepath.Join(spoolTrustDir(), "trust.json")
}

func spoolTrustEnvPath() string {
	return filepath.Join(spoolTrustDir(), "spool-trust.env")
}

func loadSpoolTrust() spoolTrustFile {
	spoolTrustMu.Lock()
	defer spoolTrustMu.Unlock()
	raw, err := os.ReadFile(spoolTrustJSONPath())
	if err != nil {
		return spoolTrustFile{}
	}
	var t spoolTrustFile
	if json.Unmarshal(raw, &t) != nil || t.Keys == nil {
		t.Keys = nil
	}
	return t
}

func saveSpoolTrust(t spoolTrustFile) error {
	spoolTrustMu.Lock()
	defer spoolTrustMu.Unlock()
	if err := os.MkdirAll(spoolTrustKeysDir(), 0o700); err != nil {
		return err
	}
	raw, err := json.MarshalIndent(t, "", "  ")
	if err != nil {
		return err
	}
	tmp := spoolTrustJSONPath() + ".tmp"
	if err := os.WriteFile(tmp, raw, 0o600); err != nil {
		return err
	}
	if err := os.Rename(tmp, spoolTrustJSONPath()); err != nil {
		return err
	}
	return writeSpoolTrustEnvLocked(t)
}

func writeSpoolTrustEnvLocked(t spoolTrustFile) error {
	req := "0"
	if t.RequireSignature {
		req = "1"
	}
	var b strings.Builder
	b.WriteString("# Generated by admin-ui marketplace trust. Point core at this dir / source this file.\n")
	fmt.Fprintf(&b, "MUXCORE_SPOOL_REQUIRE_SIGNATURE=%s\n", req)
	fmt.Fprintf(&b, "MUXCORE_SPOOL_TRUSTED_KEYS_DIR=%s\n", spoolTrustKeysDir())
	if strings.TrimSpace(t.AllowedPublishers) != "" {
		fmt.Fprintf(&b, "MUXCORE_SPOOL_ALLOWED_PUBLISHERS=%s\n", strings.TrimSpace(t.AllowedPublishers))
	}
	tmp := spoolTrustEnvPath() + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o600); err != nil {
		return err
	}
	return os.Rename(tmp, spoolTrustEnvPath())
}

func fingerprintPub(pub ed25519.PublicKey) string {
	sum := sha256.Sum256(pub)
	return hex.EncodeToString(sum[:8])
}

// parseSpoolPublicKey mirrors core/internal/spool.ParsePublicKey formats
// (raw/hex/base64/PEM/minisign .pub) so admin-ui can validate before persist.
func parseSpoolPublicKey(raw []byte) (ed25519.PublicKey, error) {
	if len(raw) == ed25519.PublicKeySize {
		out := make(ed25519.PublicKey, ed25519.PublicKeySize)
		copy(out, raw)
		return out, nil
	}
	text := strings.TrimSpace(string(raw))
	if strings.HasPrefix(text, "-----BEGIN") {
		block, _ := pem.Decode(raw)
		if block == nil {
			return nil, fmt.Errorf("invalid PEM public key")
		}
		if len(block.Bytes) >= ed25519.PublicKeySize {
			key := block.Bytes[len(block.Bytes)-ed25519.PublicKeySize:]
			out := make(ed25519.PublicKey, ed25519.PublicKeySize)
			copy(out, key)
			return out, nil
		}
		return nil, fmt.Errorf("PEM public key too short")
	}
	if strings.Contains(text, "untrusted comment:") || strings.HasPrefix(text, "RW") {
		lines := strings.Split(text, "\n")
		var b64 string
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "untrusted comment:") {
				continue
			}
			b64 = line
			break
		}
		if b64 == "" {
			return nil, fmt.Errorf("minisign public key: missing key line")
		}
		decoded, err := base64.StdEncoding.DecodeString(b64)
		if err != nil {
			return nil, fmt.Errorf("minisign public key base64: %w", err)
		}
		if len(decoded) < 10+ed25519.PublicKeySize {
			return nil, fmt.Errorf("minisign public key too short (%d)", len(decoded))
		}
		out := make(ed25519.PublicKey, ed25519.PublicKeySize)
		copy(out, decoded[10:10+ed25519.PublicKeySize])
		return out, nil
	}
	if b, err := hex.DecodeString(text); err == nil && len(b) == ed25519.PublicKeySize {
		return ed25519.PublicKey(b), nil
	}
	if b, err := base64.StdEncoding.DecodeString(text); err == nil && len(b) == ed25519.PublicKeySize {
		return ed25519.PublicKey(b), nil
	}
	if b, err := base64.RawStdEncoding.DecodeString(text); err == nil && len(b) == ed25519.PublicKeySize {
		return ed25519.PublicKey(b), nil
	}
	return nil, fmt.Errorf("unrecognized ed25519 public key format")
}

func (h *Handler) MarketplaceTrustPage(w http.ResponseWriter, r *http.Request) {
	data := h.marketplaceTrustData(r)
	content := templates.MarketplaceTrustPage(data)
	nav := h.nav(r.URL.Path)
	h.render(w, r, templates.Layout("Marketplace trust", nav, content))
}

func (h *Handler) marketplaceTrustData(r *http.Request) templates.MarketplaceTrustData {
	t := loadSpoolTrust()
	data := templates.MarketplaceTrustData{
		RequireSignaturePref: t.RequireSignature,
		RequireSignatureEnv:  os.Getenv("MUXCORE_SPOOL_REQUIRE_SIGNATURE") == "1",
		PublicKeyEnv:         strings.TrimSpace(os.Getenv("MUXCORE_SPOOL_PUBLIC_KEY")),
		TrustedKeysDirEnv:    strings.TrimSpace(os.Getenv("MUXCORE_SPOOL_TRUSTED_KEYS_DIR")),
		AllowedPublishersEnv: strings.TrimSpace(os.Getenv("MUXCORE_SPOOL_ALLOWED_PUBLISHERS")),
		AllowedPublishers:    t.AllowedPublishers,
		TrustDir:             spoolTrustDir(),
		KeysDir:              spoolTrustKeysDir(),
		EnvFile:              spoolTrustEnvPath(),
		Saved:                r.URL.Query().Get("saved") == "1",
		Error:                r.URL.Query().Get("error"),
	}
	for _, k := range t.Keys {
		data.Keys = append(data.Keys, templates.MarketplaceTrustKey{
			ID:          k.ID,
			Label:       k.Label,
			Fingerprint: k.Fingerprint,
			Filename:    k.Filename,
			AddedAt:     k.AddedAt,
		})
	}
	return data
}

func (h *Handler) MarketplaceTrustSaveSettings(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Redirect(w, r, "/marketplace/trust?error="+url.QueryEscape(err.Error()), http.StatusSeeOther)
		return
	}
	t := loadSpoolTrust()
	t.RequireSignature = r.FormValue("require_signature") == "1"
	t.AllowedPublishers = strings.TrimSpace(r.FormValue("allowed_publishers"))
	if err := saveSpoolTrust(t); err != nil {
		http.Redirect(w, r, "/marketplace/trust?error="+url.QueryEscape(err.Error()), http.StatusSeeOther)
		return
	}
	actor := "admin"
	if sess := SessionFromContext(r.Context()); sess != nil && sess.UserID != "" {
		actor = sess.UserID
	}
	h.auditLog(r.Context(), actor, "marketplace.trust.settings", "spool", "trust", map[string]string{
		"require_signature":  fmt.Sprintf("%v", t.RequireSignature),
		"allowed_publishers": t.AllowedPublishers,
	})
	http.Redirect(w, r, "/marketplace/trust?saved=1", http.StatusSeeOther)
}

func (h *Handler) MarketplaceTrustAddKey(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Redirect(w, r, "/marketplace/trust?error="+url.QueryEscape(err.Error()), http.StatusSeeOther)
		return
	}
	label := strings.TrimSpace(r.FormValue("label"))
	material := strings.TrimSpace(r.FormValue("public_key"))
	if material == "" {
		http.Redirect(w, r, "/marketplace/trust?error="+url.QueryEscape("public key required"), http.StatusSeeOther)
		return
	}
	pub, err := parseSpoolPublicKey([]byte(material))
	if err != nil {
		http.Redirect(w, r, "/marketplace/trust?error="+url.QueryEscape("invalid public key: "+err.Error()), http.StatusSeeOther)
		return
	}
	fp := fingerprintPub(pub)
	id := fp
	if label == "" {
		label = "key-" + fp[:8]
	}
	filename := id + ".pub"
	if err := os.MkdirAll(spoolTrustKeysDir(), 0o700); err != nil {
		http.Redirect(w, r, "/marketplace/trust?error="+url.QueryEscape(err.Error()), http.StatusSeeOther)
		return
	}
	keyPath := filepath.Join(spoolTrustKeysDir(), filename)
	if !strings.HasSuffix(material, "\n") {
		material += "\n"
	}
	if err := os.WriteFile(keyPath, []byte(material), 0o600); err != nil {
		http.Redirect(w, r, "/marketplace/trust?error="+url.QueryEscape(err.Error()), http.StatusSeeOther)
		return
	}

	t := loadSpoolTrust()
	for _, existing := range t.Keys {
		if existing.Fingerprint == fp {
			http.Redirect(w, r, "/marketplace/trust?error="+url.QueryEscape("key already trusted (fingerprint "+fp+")"), http.StatusSeeOther)
			return
		}
	}
	t.Keys = append(t.Keys, spoolTrustKeyMeta{
		ID:          id,
		Label:       label,
		Fingerprint: fp,
		Filename:    filename,
		AddedAt:     time.Now().UTC().Format(time.RFC3339),
	})
	if err := saveSpoolTrust(t); err != nil {
		http.Redirect(w, r, "/marketplace/trust?error="+url.QueryEscape(err.Error()), http.StatusSeeOther)
		return
	}
	actor := "admin"
	if sess := SessionFromContext(r.Context()); sess != nil && sess.UserID != "" {
		actor = sess.UserID
	}
	h.auditLog(r.Context(), actor, "marketplace.trust.key.add", "spool", id, map[string]string{
		"label":       label,
		"fingerprint": fp,
	})
	http.Redirect(w, r, "/marketplace/trust?saved=1", http.StatusSeeOther)
}

func (h *Handler) MarketplaceTrustRevokeKey(w http.ResponseWriter, r *http.Request) {
	id := strings.TrimSpace(r.PathValue("id"))
	if id == "" {
		http.Redirect(w, r, "/marketplace/trust?error="+url.QueryEscape("key id required"), http.StatusSeeOther)
		return
	}
	t := loadSpoolTrust()
	var kept []spoolTrustKeyMeta
	var removed *spoolTrustKeyMeta
	for i := range t.Keys {
		if t.Keys[i].ID == id {
			removed = &t.Keys[i]
			continue
		}
		kept = append(kept, t.Keys[i])
	}
	if removed == nil {
		http.Redirect(w, r, "/marketplace/trust?error="+url.QueryEscape("key not found"), http.StatusSeeOther)
		return
	}
	_ = os.Remove(filepath.Join(spoolTrustKeysDir(), removed.Filename))
	t.Keys = kept
	if err := saveSpoolTrust(t); err != nil {
		http.Redirect(w, r, "/marketplace/trust?error="+url.QueryEscape(err.Error()), http.StatusSeeOther)
		return
	}
	actor := "admin"
	if sess := SessionFromContext(r.Context()); sess != nil && sess.UserID != "" {
		actor = sess.UserID
	}
	h.auditLog(r.Context(), actor, "marketplace.trust.key.revoke", "spool", id, map[string]string{
		"fingerprint": removed.Fingerprint,
	})
	http.Redirect(w, r, "/marketplace/trust?saved=1", http.StatusSeeOther)
}
